title: Karim Eldefrawy
description: Cryptography, Cybersecurity, Privacy
url: https://keldefrawy.github.io
baseurl: ""
theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap

collections:
  papers:
    output: true
    permalink: /knowledge/papers/:name/

defaults:
  - scope:
      path: ""
      type: papers
    values:
      layout: knowledge-map
